require: rubocop-performance
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
Layout/LineLength:
  Max: 130
Metrics/AbcSize:
  Max: 21
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 20
