require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
LineLength:
  Max: 130
MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
