require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 20
