AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
LineLength:
  Enabled: false
MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
